
#line 3 "lex.akashM.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define yy_create_buffer akashM_create_buffer
#define yy_delete_buffer akashM_delete_buffer
#define yy_flex_debug akashM_flex_debug
#define yy_init_buffer akashM_init_buffer
#define yy_flush_buffer akashM_flush_buffer
#define yy_load_buffer_state akashM_load_buffer_state
#define yy_switch_to_buffer akashM_switch_to_buffer
#define yyin akashMin
#define yyleng akashMleng
#define yylex akashMlex
#define yylineno akashMlineno
#define yyout akashMout
#define yyrestart akashMrestart
#define yytext akashMtext
#define yywrap akashMwrap
#define yyalloc akashMalloc
#define yyrealloc akashMrealloc
#define yyfree akashMfree

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 0
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE akashMrestart(akashMin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t akashMleng;

extern FILE *akashMin, *akashMout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up akashMtext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up akashMtext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via akashMrestart()), so that the user can continue scanning by
	 * just pointing akashMin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when akashMtext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t akashMleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow akashMwrap()'s to do buffer switches
 * instead of setting up a fresh akashMin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void akashMrestart (FILE *input_file  );
void akashM_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE akashM_create_buffer (FILE *file,int size  );
void akashM_delete_buffer (YY_BUFFER_STATE b  );
void akashM_flush_buffer (YY_BUFFER_STATE b  );
void akashMpush_buffer_state (YY_BUFFER_STATE new_buffer  );
void akashMpop_buffer_state (void );

static void akashMensure_buffer_stack (void );
static void akashM_load_buffer_state (void );
static void akashM_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER akashM_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE akashM_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE akashM_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE akashM_scan_bytes (yyconst char *bytes,yy_size_t len  );

void *akashMalloc (yy_size_t  );
void *akashMrealloc (void *,yy_size_t  );
void akashMfree (void *  );

#define yy_new_buffer akashM_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        akashMensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            akashM_create_buffer(akashMin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        akashMensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            akashM_create_buffer(akashMin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *akashMin = (FILE *) 0, *akashMout = (FILE *) 0;

typedef int yy_state_type;

extern int akashMlineno;

int akashMlineno = 1;

extern char *akashMtext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr akashMtext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
#if defined(__GNUC__) && __GNUC__ >= 3
__attribute__((__noreturn__))
#endif
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up akashMtext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	akashMleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 76
#define YY_END_OF_BUFFER 77
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[334] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       77,    5,    3,    4,    2,    5,   13,   11,   12,   10,
       13,   27,   20,   21,   19,   25,   22,   27,   27,   27,
       27,   27,   27,   27,   27,   27,   32,   29,   30,   31,
       28,   51,   45,   46,   44,   50,   47,   51,   51,   51,
       51,   51,   51,   51,   51,   51,   68,   66,   67,   65,
       68,   63,   68,   75,   73,   74,   72,   71,   70,   75,
       56,   53,   54,   55,   52,   37,   34,   35,   36,   33,
       61,   58,   59,   60,   57,    0,    0,   25,    0,    0,

        0,    0,    0,    0,    0,    0,    0,   50,    0,    0,
        0,    0,    0,    0,    0,    0,    0,   64,    0,    0,
       71,    0,   33,   57,    0,    0,    0,    0,    0,    0,
       23,    0,    0,    0,    0,    0,    0,    0,    0,   48,
        0,    0,    0,    0,   64,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,   24,    0,    0,    0,    0,
        0,    0,    0,   49,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,   14,    0,    0,    0,    0,    0,
       38,    0,    0,    0,   69,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       62,    0,    0,    0,   26,   15,    0,    0,    0,   43,
       39,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,   18,    0,    0,   42,    0,
        0,    0,    0,   16,    0,   40,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    8,    9,    0,

        0,    0,    0,    0,    0,    0,   17,   41,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    7,    6,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    1,    0
    } ;

static yyconst YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    2,
        1,    1,    3,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    1,    1,    5,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    6,    7,    8,    9,    8,
        8,    8,    8,    8,    8,    8,    8,    1,    1,    1,
       10,    1,    1,    1,    1,    1,   11,    1,    1,    1,
        1,    1,   12,    1,    1,    1,   13,    1,    1,   14,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
       15,    1,   16,    1,   17,    1,   18,   19,   20,   21,

       22,   23,   24,   25,   26,    1,   27,   28,   29,   30,
       31,   32,   33,   34,   35,   36,   37,   38,   39,    1,
       40,   41,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst YY_CHAR yy_meta[42] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1
    } ;

static yyconst flex_uint16_t yy_base[344] =
    {   0,
        0,    4,    8,   11,   25,   63,   14,   28,  101,  139,
      177,  199,  221,  248,   37,   48,   66,   76,   85,  104,
      412,  413,  413,  413,  413,  407,  413,  413,  413,  413,
      378,  413,  413,  413,  413,   11,  413,  374,  380,  389,
      388,  371,  382,  381,  368,  367,  413,  413,  413,  413,
      413,  413,  413,  413,  413,   13,  413,  365,  371,  380,
      379,  362,  373,  372,  359,  358,  413,  413,  413,  413,
       54,  413,  357,  413,  413,  413,  413,   28,  413,  372,
      413,  413,  413,  413,  413,  413,  413,  413,  413,   46,
      413,  413,  413,  413,   68,  378,  366,   92,  352,  355,

      365,  356,  346,  348,  349,  343,  353,  106,  343,  346,
      356,  347,  337,  339,  340,  334,  344,  108,  117,  347,
      119,  332,  122,  130,  336,  332,  334,  344,  338,  327,
      413,  338,  332,  337,  322,  326,  336,  330,  319,  413,
      330,  324,  329,  314,  136,  316,  326,  318,  323,  325,
      317,  321,  320,  319,  322,  413,  317,  318,  310,  314,
      313,  312,  315,  413,  310,  294,  300,  300,  311,  301,
      309,  308,  304,  303,  286,  295,  303,  302,  298,  297,
      280,  293,  294,  282,  283,  293,  275,  274,  272,  285,
      281,  287,  269,  268,  266,  279,  275,  269,  258,  267,

      265,  259,  268,  267,  413,  263,  257,  254,  263,  262,
      413,  258,  252,  265,  413,  280,  262,  256,  240,  239,
      257,  247,  251,  234,  233,  251,  241,  231,  250,  247,
      230,  245,  244,  235,  227,  225,  240,  239,  230,  222,
      413,  224,  226,  227,  413,  413,  212,  223,  220,  413,
      413,  209,  220,  213,  235,  205,  223,  214,  202,  220,
      211,  212,  132,  194,  201,  413,  192,  196,  413,  201,
      195,  187,  211,  413,  188,  413,  187,  193,  182,  197,
      197,  185,  184,  207,  188,  177,  125,  179,  178,  176,
      182,  181,  176,  175,  174,  173,  166,  413,  413,  173,

      172,  149,  148,  156,  163,  162,  413,  413,  155,  151,
      149,  168,  148,  147,  145,  150,  149,  133,  413,  413,
      129,  157,  143,  143,  140,  115,  132,  114,  101,   88,
       96,  413,  413,   97,   95,   91,   89,   55,   48,   45,
       41,   24,    0
    } ;

static yyconst flex_int16_t yy_def[344] =
    {   0,
      334,  334,  335,  335,  336,  336,  337,  337,  338,  338,
      339,  339,  340,  340,  341,  341,  342,  342,  343,  343,
      333,  333,  333,  333,  333,  333,  333,  333,  333,  333,
      333,  333,  333,  333,  333,  333,  333,  333,  333,  333,
      333,  333,  333,  333,  333,  333,  333,  333,  333,  333,
      333,  333,  333,  333,  333,  333,  333,  333,  333,  333,
      333,  333,  333,  333,  333,  333,  333,  333,  333,  333,
      333,  333,  333,  333,  333,  333,  333,  333,  333,  333,
      333,  333,  333,  333,  333,  333,  333,  333,  333,  333,
      333,  333,  333,  333,  333,  333,  333,  333,  333,  333,

      333,  333,  333,  333,  333,  333,  333,  333,  333,  333,
      333,  333,  333,  333,  333,  333,  333,  333,  333,  333,
      333,  333,  333,  333,  333,  333,  333,  333,  333,  333,
      333,  333,  333,  333,  333,  333,  333,  333,  333,  333,
      333,  333,  333,  333,  333,  333,  333,  333,  333,  333,
      333,  333,  333,  333,  333,  333,  333,  333,  333,  333,
      333,  333,  333,  333,  333,  333,  333,  333,  333,  333,
      333,  333,  333,  333,  333,  333,  333,  333,  333,  333,
      333,  333,  333,  333,  333,  333,  333,  333,  333,  333,
      333,  333,  333,  333,  333,  333,  333,  333,  333,  333,

      333,  333,  333,  333,  333,  333,  333,  333,  333,  333,
      333,  333,  333,  333,  333,  333,  333,  333,  333,  333,
      333,  333,  333,  333,  333,  333,  333,  333,  333,  333,
      333,  333,  333,  333,  333,  333,  333,  333,  333,  333,
      333,  333,  333,  333,  333,  333,  333,  333,  333,  333,
      333,  333,  333,  333,  333,  333,  333,  333,  333,  333,
      333,  333,  333,  333,  333,  333,  333,  333,  333,  333,
      333,  333,  333,  333,  333,  333,  333,  333,  333,  333,
      333,  333,  333,  333,  333,  333,  333,  333,  333,  333,
      333,  333,  333,  333,  333,  333,  333,  333,  333,  333,

      333,  333,  333,  333,  333,  333,  333,  333,  333,  333,
      333,  333,  333,  333,  333,  333,  333,  333,  333,  333,
      333,  333,  333,  333,  333,  333,  333,  333,  333,  333,
      333,  333,    0,  333,  333,  333,  333,  333,  333,  333,
      333,  333,  333
    } ;

static yyconst flex_uint16_t yy_nxt[455] =
    {   0,
       91,   23,   24,   25,   26,   23,   24,   25,   26,   28,
       29,   30,   28,   29,   30,   48,   49,   50,   98,   98,
      108,  108,   31,   51,   86,   31,   33,   34,   35,   48,
       49,   50,   36,   36,   37,  121,  121,   51,   82,   83,
       84,   81,   38,   39,   40,   74,   85,   41,   67,   82,
       83,   84,   42,  123,  123,   52,   43,   85,   44,  118,
       45,  119,  119,   46,   33,   34,   35,   87,   88,   89,
       36,   36,   37,   90,   90,  124,  124,   87,   88,   89,
       38,   39,   40,   90,   90,   41,   92,   93,   94,   47,
       42,   32,   95,   95,   43,   27,   44,   22,   45,   98,

       98,   46,   53,   54,   55,   92,   93,   94,   56,   56,
       57,   95,   95,  108,  108,  145,  145,  332,   58,   59,
       60,  331,  118,   61,  119,  119,  121,  121,   62,  123,
      123,  330,   63,  329,   64,  328,   65,  124,  124,   66,
       53,   54,   55,  145,  145,  293,   56,   56,   57,  327,
      294,  271,  272,  326,  325,  324,   58,   59,   60,  273,
      323,   61,  322,  321,  320,  319,   62,  318,  317,  316,
       63,  315,   64,  314,   65,  313,  312,   66,   68,   69,
       70,  311,  310,  309,   71,   71,   72,  308,  307,  306,
      305,  304,  303,  302,  301,  300,  299,  298,  297,   73,

       68,   69,   70,  296,  295,  292,   71,   71,   72,  291,
      290,  289,  288,  287,  286,  285,  284,  283,  282,  281,
      280,   73,   75,   76,   77,  279,  278,  277,   78,   78,
       79,  276,  275,  274,  270,  269,  268,  267,  266,  265,
      264,  263,  262,  261,  260,  259,  258,  257,   80,   75,
       76,   77,  256,  255,  254,   78,   78,   79,  253,  252,
      251,  250,  249,  248,  247,  246,  245,  244,  243,  242,
      241,  240,  239,  238,  237,   80,  236,  235,  234,  233,
      232,  231,  230,  229,  228,  227,  226,  225,  224,  223,
      222,  221,  220,  219,  218,  217,  216,  215,  214,  213,

      212,  211,  210,  209,  208,  207,  206,  205,  204,  203,
      202,  201,  200,  199,  198,  197,  196,  195,  194,  193,
      192,  191,  190,  189,  188,  187,  186,  185,  184,  183,
      182,  181,  180,  179,  164,  178,  177,  176,  175,  174,
      173,  156,  172,  171,  170,  169,  168,  167,  166,  165,
      164,  163,  162,  161,  160,  159,  158,  157,  156,  155,
      154,  153,  152,  151,  150,  149,  148,  147,  146,  144,
      143,  142,  141,  140,  139,  138,  137,  136,  135,  134,
      133,  132,  131,  130,  129,  128,  127,  126,  125,  122,
      120,  117,  116,  115,  114,  113,  112,  111,  110,  109,

      107,  106,  105,  104,  103,  102,  101,  100,   99,   97,
       96,  333,   21,  333,  333,  333,  333,  333,  333,  333,
      333,  333,  333,  333,  333,  333,  333,  333,  333,  333,
      333,  333,  333,  333,  333,  333,  333,  333,  333,  333,
      333,  333,  333,  333,  333,  333,  333,  333,  333,  333,
      333,  333,  333,  333
    } ;

static yyconst flex_int16_t yy_chk[455] =
    {   0,
      343,    1,    1,    1,    1,    2,    2,    2,    2,    3,
        3,    3,    4,    4,    4,    7,    7,    7,   36,   36,
       56,   56,    3,    7,  342,    4,    5,    5,    5,    8,
        8,    8,    5,    5,    5,   78,   78,    8,   15,   15,
       15,  341,    5,    5,    5,  340,   15,    5,  339,   16,
       16,   16,    5,   90,   90,  338,    5,   16,    5,   71,
        5,   71,   71,    5,    6,    6,    6,   17,   17,   17,
        6,    6,    6,   17,   17,   95,   95,   18,   18,   18,
        6,    6,    6,   18,   18,    6,   19,   19,   19,  337,
        6,  336,   19,   19,    6,  335,    6,  334,    6,   98,

       98,    6,    9,    9,    9,   20,   20,   20,    9,    9,
        9,   20,   20,  108,  108,  118,  118,  331,    9,    9,
        9,  330,  119,    9,  119,  119,  121,  121,    9,  123,
      123,  329,    9,  328,    9,  327,    9,  124,  124,    9,
       10,   10,   10,  145,  145,  287,   10,   10,   10,  326,
      287,  263,  263,  325,  324,  323,   10,   10,   10,  263,
      322,   10,  321,  318,  317,  316,   10,  315,  314,  313,
       10,  312,   10,  311,   10,  310,  309,   10,   11,   11,
       11,  306,  305,  304,   11,   11,   11,  303,  302,  301,
      300,  297,  296,  295,  294,  293,  292,  291,  290,   11,

       12,   12,   12,  289,  288,  286,   12,   12,   12,  285,
      284,  283,  282,  281,  280,  279,  278,  277,  275,  273,
      272,   12,   13,   13,   13,  271,  270,  268,   13,   13,
       13,  267,  265,  264,  262,  261,  260,  259,  258,  257,
      256,  255,  254,  253,  252,  249,  248,  247,   13,   14,
       14,   14,  244,  243,  242,   14,   14,   14,  240,  239,
      238,  237,  236,  235,  234,  233,  232,  231,  230,  229,
      228,  227,  226,  225,  224,   14,  223,  222,  221,  220,
      219,  218,  217,  216,  214,  213,  212,  210,  209,  208,
      207,  206,  204,  203,  202,  201,  200,  199,  198,  197,

      196,  195,  194,  193,  192,  191,  190,  189,  188,  187,
      186,  185,  184,  183,  182,  181,  180,  179,  178,  177,
      176,  175,  174,  173,  172,  171,  170,  169,  168,  167,
      166,  165,  163,  162,  161,  160,  159,  158,  157,  155,
      154,  153,  152,  151,  150,  149,  148,  147,  146,  144,
      143,  142,  141,  139,  138,  137,  136,  135,  134,  133,
      132,  130,  129,  128,  127,  126,  125,  122,  120,  117,
      116,  115,  114,  113,  112,  111,  110,  109,  107,  106,
      105,  104,  103,  102,  101,  100,   99,   97,   96,   80,
       73,   66,   65,   64,   63,   62,   61,   60,   59,   58,

       46,   45,   44,   43,   42,   41,   40,   39,   38,   31,
       26,   21,  333,  333,  333,  333,  333,  333,  333,  333,
      333,  333,  333,  333,  333,  333,  333,  333,  333,  333,
      333,  333,  333,  333,  333,  333,  333,  333,  333,  333,
      333,  333,  333,  333,  333,  333,  333,  333,  333,  333,
      333,  333,  333,  333
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int akashM_flex_debug;
int akashM_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *akashMtext;
#line 1 "tokenizer2.l"
#line 2 "tokenizer2.l"
	#include "cache.h"
	#include "main.h"
	#include "parser2.tab.h"
	void akashMerror ( char *);
	 #define akashMSTYPE int
	int akashMparse ( void );
	//extern int akashMdebug;










#line 714 "lex.akashM.c"

#define INITIAL 0
#define STAGE 1
#define ICACHE 2
#define EQX 3
#define DCACHE 4
#define CORE 5
#define DRAM 6
#define EQ2 7
#define ENDICACHE 8
#define ENDDCACHE 9

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int akashMlex_destroy (void );

int akashMget_debug (void );

void akashMset_debug (int debug_flag  );

YY_EXTRA_TYPE akashMget_extra (void );

void akashMset_extra (YY_EXTRA_TYPE user_defined  );

FILE *akashMget_in (void );

void akashMset_in  (FILE * _in_str  );

FILE *akashMget_out (void );

void akashMset_out  (FILE * _out_str  );

yy_size_t akashMget_leng (void );

char *akashMget_text (void );

int akashMget_lineno (void );

void akashMset_lineno (int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int akashMwrap (void );
#else
extern int akashMwrap (void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput (int c,char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( akashMtext, akashMleng, 1, akashMout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( akashMin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( akashMin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, akashMin))==0 && ferror(akashMin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(akashMin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int akashMlex (void);

#define YY_DECL int akashMlex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after akashMtext and akashMleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! akashMin )
			akashMin = stdin;

		if ( ! akashMout )
			akashMout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			akashMensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				akashM_create_buffer(akashMin,YY_BUF_SIZE );
		}

		akashM_load_buffer_state( );
		}

	{
#line 21 "tokenizer2.l"

#line 943 "lex.akashM.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of akashMtext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 334 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 413 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 22 "tokenizer2.l"
{BEGIN STAGE;}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 23 "tokenizer2.l"
{BEGIN INITIAL;}
	YY_BREAK
case 3:
/* rule 3 can match eol */
YY_RULE_SETUP
#line 24 "tokenizer2.l"
{BEGIN INITIAL;}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 25 "tokenizer2.l"
{BEGIN INITIAL;}
	YY_BREAK
case YY_STATE_EOF(INITIAL):
#line 26 "tokenizer2.l"
{ BEGIN INITIAL;return END_OF_FILE;}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 27 "tokenizer2.l"
{printf("Wrong Input\n"); exit(0);}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 28 "tokenizer2.l"
{BEGIN ICACHE;}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 29 "tokenizer2.l"
{BEGIN DCACHE;}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 30 "tokenizer2.l"
{BEGIN CORE;}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 31 "tokenizer2.l"
{BEGIN DRAM;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 32 "tokenizer2.l"
{BEGIN STAGE;}
	YY_BREAK
case 11:
/* rule 11 can match eol */
YY_RULE_SETUP
#line 33 "tokenizer2.l"
{BEGIN STAGE;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 34 "tokenizer2.l"
{BEGIN STAGE;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 35 "tokenizer2.l"
{printf("Wrong Input\n"); exit(0);}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 37 "tokenizer2.l"
{BEGIN ICACHE; return PER1; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 38 "tokenizer2.l"
{BEGIN ICACHE; return CAC1; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 39 "tokenizer2.l"
{BEGIN ICACHE; return ASS1; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 40 "tokenizer2.l"
{BEGIN ICACHE; return REP1; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 41 "tokenizer2.l"
{BEGIN ICACHE; return WRT1; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 42 "tokenizer2.l"
{BEGIN ICACHE;}
	YY_BREAK
case 20:
/* rule 20 can match eol */
YY_RULE_SETUP
#line 43 "tokenizer2.l"
{BEGIN ICACHE;}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 44 "tokenizer2.l"
{BEGIN ICACHE;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 45 "tokenizer2.l"
{BEGIN ICACHE;return EQ; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 46 "tokenizer2.l"
{BEGIN ICACHE;return LRU; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 47 "tokenizer2.l"
{akashMlval.str= (char*)malloc(sizeof(char)*akashMleng + 2);
	strcpy(akashMlval.str, akashMtext);BEGIN ICACHE;return BOOL;}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 49 "tokenizer2.l"
{akashMlval.intval = atoi(akashMtext);BEGIN ICACHE;return VAL; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 50 "tokenizer2.l"
{BEGIN EQX;return BS1;}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 51 "tokenizer2.l"
{printf("Wrong Input\n"); exit(0);}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 53 "tokenizer2.l"
{BEGIN ENDICACHE;return EQ;}
	YY_BREAK
case 29:
/* rule 29 can match eol */
YY_RULE_SETUP
#line 54 "tokenizer2.l"
{BEGIN EQX;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 55 "tokenizer2.l"
{BEGIN EQX;}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 56 "tokenizer2.l"
{BEGIN EQX;}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 57 "tokenizer2.l"
{printf("Wrong Input\n"); exit(0);}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 59 "tokenizer2.l"
{akashMlval.intval = atoi(akashMtext);BEGIN STAGE;return VAL;}
	YY_BREAK
case 34:
/* rule 34 can match eol */
YY_RULE_SETUP
#line 60 "tokenizer2.l"
{BEGIN ENDICACHE;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 61 "tokenizer2.l"
{BEGIN ENDICACHE;}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 62 "tokenizer2.l"
{BEGIN ENDICACHE;}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 63 "tokenizer2.l"
{printf("Wrong Input\n"); exit(0);}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 66 "tokenizer2.l"
{BEGIN DCACHE; return PER2; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 67 "tokenizer2.l"
{BEGIN DCACHE; return CAC2; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 68 "tokenizer2.l"
{BEGIN DCACHE; return ASS2; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 69 "tokenizer2.l"
{BEGIN DCACHE; return REP2; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 70 "tokenizer2.l"
{BEGIN DCACHE; return WRT2; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 71 "tokenizer2.l"
{ BEGIN EQ2;return BS2;}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 72 "tokenizer2.l"
{BEGIN DCACHE;}
	YY_BREAK
case 45:
/* rule 45 can match eol */
YY_RULE_SETUP
#line 73 "tokenizer2.l"
{BEGIN DCACHE;}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 74 "tokenizer2.l"
{BEGIN DCACHE;}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 75 "tokenizer2.l"
{BEGIN DCACHE;return EQ; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 76 "tokenizer2.l"
{BEGIN DCACHE; return LRU;}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 77 "tokenizer2.l"
{akashMlval.str= (char*)malloc(sizeof(char)*akashMleng + 2);
	strcpy(akashMlval.str, akashMtext);BEGIN DCACHE;return BOOL;}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 79 "tokenizer2.l"
{akashMlval.intval = atoi(akashMtext);BEGIN DCACHE;return VAL; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 80 "tokenizer2.l"
{printf("Wrong Input\n"); exit(0);}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 83 "tokenizer2.l"
{BEGIN ENDDCACHE;return EQ; }
	YY_BREAK
case 53:
/* rule 53 can match eol */
YY_RULE_SETUP
#line 84 "tokenizer2.l"
{BEGIN EQ2;}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 85 "tokenizer2.l"
{BEGIN EQ2;}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 86 "tokenizer2.l"
{BEGIN EQ2;}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 87 "tokenizer2.l"
{printf("Wrong Input\n"); exit(0);}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 90 "tokenizer2.l"
{akashMlval.intval = atoi(akashMtext);BEGIN STAGE;return VAL; }
	YY_BREAK
case 58:
/* rule 58 can match eol */
YY_RULE_SETUP
#line 91 "tokenizer2.l"
{BEGIN ENDDCACHE;}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 92 "tokenizer2.l"
{BEGIN ENDDCACHE;}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 93 "tokenizer2.l"
{BEGIN ENDDCACHE;}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 94 "tokenizer2.l"
{printf("Wrong Input\n"); exit(0);}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 98 "tokenizer2.l"
{BEGIN CORE;return FRQ; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 99 "tokenizer2.l"
{BEGIN CORE;return EQ; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 100 "tokenizer2.l"
{akashMlval.floatval = atof(akashMtext); BEGIN STAGE;return FLOAT;}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 101 "tokenizer2.l"
{BEGIN CORE;}
	YY_BREAK
case 66:
/* rule 66 can match eol */
YY_RULE_SETUP
#line 102 "tokenizer2.l"
{BEGIN CORE;}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 103 "tokenizer2.l"
{BEGIN CORE;}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 104 "tokenizer2.l"
{printf("Wrong Input\n"); exit(0);}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 106 "tokenizer2.l"
{BEGIN DRAM;return LAT;}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 107 "tokenizer2.l"
{BEGIN DRAM;return EQ; }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 108 "tokenizer2.l"
{akashMlval.intval = atoi(akashMtext);BEGIN INITIAL;return VAL;}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 109 "tokenizer2.l"
{BEGIN DRAM;}
	YY_BREAK
case 73:
/* rule 73 can match eol */
YY_RULE_SETUP
#line 110 "tokenizer2.l"
{BEGIN DRAM;}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 111 "tokenizer2.l"
{BEGIN DRAM;}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 112 "tokenizer2.l"
{printf("Wrong Input\n"); exit(0);}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 113 "tokenizer2.l"
ECHO;
	YY_BREAK
#line 1396 "lex.akashM.c"
case YY_STATE_EOF(STAGE):
case YY_STATE_EOF(ICACHE):
case YY_STATE_EOF(EQX):
case YY_STATE_EOF(DCACHE):
case YY_STATE_EOF(CORE):
case YY_STATE_EOF(DRAM):
case YY_STATE_EOF(EQ2):
case YY_STATE_EOF(ENDICACHE):
case YY_STATE_EOF(ENDDCACHE):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed akashMin at a new source and called
			 * akashMlex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = akashMin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( akashMwrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * akashMtext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of akashMlex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	yy_size_t number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (yy_size_t) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					akashMrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			akashMrestart(akashMin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((int) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) akashMrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 334 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 334 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 333);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up akashMtext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		yy_size_t number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					akashMrestart(akashMin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( akashMwrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve akashMtext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void akashMrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        akashMensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            akashM_create_buffer(akashMin,YY_BUF_SIZE );
	}

	akashM_init_buffer(YY_CURRENT_BUFFER,input_file );
	akashM_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void akashM_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		akashMpop_buffer_state();
	 *		akashMpush_buffer_state(new_buffer);
     */
	akashMensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	akashM_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (akashMwrap()) processing, but the only time this flag
	 * is looked at is after akashMwrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void akashM_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	akashMin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE akashM_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) akashMalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in akashM_create_buffer()" );

	b->yy_buf_size = (yy_size_t)size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) akashMalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in akashM_create_buffer()" );

	b->yy_is_our_buffer = 1;

	akashM_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with akashM_create_buffer()
 * 
 */
    void akashM_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		akashMfree((void *) b->yy_ch_buf  );

	akashMfree((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a akashMrestart() or at EOF.
 */
    static void akashM_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	akashM_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then akashM_init_buffer was _probably_
     * called from akashMrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void akashM_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		akashM_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void akashMpush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	akashMensure_buffer_stack();

	/* This block is copied from akashM_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from akashM_switch_to_buffer. */
	akashM_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void akashMpop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	akashM_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		akashM_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void akashMensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)akashMalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in akashMensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)akashMrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in akashMensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE akashM_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) akashMalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in akashM_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	akashM_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to akashMlex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       akashM_scan_bytes() instead.
 */
YY_BUFFER_STATE akashM_scan_string (yyconst char * yystr )
{
    
	return akashM_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to akashMlex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE akashM_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	yy_size_t i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) akashMalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in akashM_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = akashM_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in akashM_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
			(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up akashMtext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		akashMtext[akashMleng] = (yy_hold_char); \
		(yy_c_buf_p) = akashMtext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		akashMleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int akashMget_lineno  (void)
{
        
    return akashMlineno;
}

/** Get the input stream.
 * 
 */
FILE *akashMget_in  (void)
{
        return akashMin;
}

/** Get the output stream.
 * 
 */
FILE *akashMget_out  (void)
{
        return akashMout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t akashMget_leng  (void)
{
        return akashMleng;
}

/** Get the current token.
 * 
 */

char *akashMget_text  (void)
{
        return akashMtext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void akashMset_lineno (int  _line_number )
{
    
    akashMlineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see akashM_switch_to_buffer
 */
void akashMset_in (FILE *  _in_str )
{
        akashMin = _in_str ;
}

void akashMset_out (FILE *  _out_str )
{
        akashMout = _out_str ;
}

int akashMget_debug  (void)
{
        return akashM_flex_debug;
}

void akashMset_debug (int  _bdebug )
{
        akashM_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from akashMlex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    akashMin = stdin;
    akashMout = stdout;
#else
    akashMin = (FILE *) 0;
    akashMout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * akashMlex_init()
     */
    return 0;
}

/* akashMlex_destroy is for both reentrant and non-reentrant scanners. */
int akashMlex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		akashM_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		akashMpop_buffer_state();
	}

	/* Destroy the stack itself. */
	akashMfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * akashMlex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *akashMalloc (yy_size_t  size )
{
			return (void *) malloc( size );
}

void *akashMrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void akashMfree (void * ptr )
{
			free( (char *) ptr );	/* see akashMrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 113 "tokenizer2.l"




void akashMerror(char* str){
	fprintf(akashMout, "SynErr");
}

int akashMwrap (void)
{
return 1;
}


